################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
__build__/3rd/amplsolvers \
__build__/3rd/amplsolvers/examples \
__build__/3rd/amplsolvers/sys.x86_64.Linux \
__build__/3rd/gaol-4.2.0/check \
__build__/3rd/gaol-4.2.0/examples \
__build__/3rd/gaol-4.2.0/gaol \
__build__/3rd/gaol-4.2.0/gdtoa \
__build__/3rd/gaol-4.2.0/gdtoa/test \
__build__/3rd/mathlib-2.1.0/src \
__build__/3rd/soplex-1.7.1/doc \
__build__/3rd/soplex-1.7.1/obj/O.linux.x86_64.gnu.opt/bin \
__build__/3rd/soplex-1.7.1/obj/O.linux.x86_64.gnu.opt/lib \
__build__/3rd/soplex-1.7.1/src \
__build__/plugins/affine/src/arithmetic \
__build__/plugins/affine/src/function \
__build__/plugins/affine/src/numeric \
__build__/plugins/ampl/src/system \
__build__/plugins/optim/main \
__build__/plugins/optim/src/bisector \
__build__/plugins/optim/src/contractor \
__build__/plugins/optim/src/loup \
__build__/plugins/optim/src/numeric \
__build__/plugins/optim/src/strategy \
__build__/plugins/pso/main \
__build__/plugins/pso/src/pso \
__build__/plugins/pso/src/strategy \
__build__/plugins/solver/main \
__build__/plugins/solver/src \
__build__/src/arithmetic \
__build__/src/bisector \
__build__/src/combinatorial \
__build__/src/contractor \
__build__/src/function \
__build__/src/numeric \
__build__/src/parser \
__build__/src/predicate \
__build__/src/set \
__build__/src/strategy \
__build__/src/symbolic \
__build__/src/system \
__build__/src/tools \
examples \
examples/slam \
plugins/affine/examples \
plugins/affine/src/arithmetic \
plugins/affine/src/function \
plugins/affine/src/numeric \
plugins/affine/tests \
plugins/affine-extended/examples \
plugins/affine-extended/src/arithmetic \
plugins/ampl/examples \
plugins/ampl/src/system \
plugins/ampl/tests \
plugins/continuation/examples \
plugins/continuation/src \
plugins/continuation/tests \
plugins/ensta-robotics/src \
plugins/ensta-robotics/tests \
plugins/interval_lib_bias \
plugins/interval_lib_direct \
plugins/interval_lib_filib \
plugins/interval_lib_gaol \
plugins/lp_lib_clp \
plugins/lp_lib_cplex \
plugins/lp_lib_none \
plugins/lp_lib_soplex \
plugins/optim \
plugins/optim/main \
plugins/optim/src/bisector \
plugins/optim/src/contractor \
plugins/optim/src/loup \
plugins/optim/src/numeric \
plugins/optim/src/strategy \
plugins/optim/tests \
plugins/param-estim/examples \
plugins/param-estim/src/cliquer \
plugins/param-estim/src \
plugins/param-estim/tests \
plugins/pso/main \
plugins/pso/src/pso \
plugins/pso/src/strategy \
plugins/solver/main \
plugins/solver/src \
src/arithmetic \
src/bisector \
src/combinatorial \
src/contractor \
src/function \
src/numeric \
src/parser \
src/predicate \
src/set \
src/strategy \
src/symbolic \
src/system \
src/tools \
tests/3rd/fmemopen \
tests \

